### ISSUE TITLE
Wooza's challenge URL is not working

### ISSUE THREAD

**Issue by rafaelflorespereira** [felipefialho/frontend-challenges#110]
https://teste-js.wooza.com.br/

**Comment by felipefialho** [comment]
Hey @rafaelflorespereira can you open a PR to fix it? 😁

**Comment by brunoromeiro** [comment]
O teste está funcional. Eu trabalhei lá, e está funcional. @rafaelflorespereira

**Comment by rafaelflorespereira** [comment]
Sure I would, but then I would spoil its surprise...lol
