### ISSUE TITLE
Translate portuguese-written challenges to english

### ISSUE THREAD

**Issue by javierojeda94** [felipefialho/frontend-challenges#53]
Almost all challenges are written in portuguese and it makes it hard for people like me who doesn't understand it.

It would be cool if someone could take some time to translate them to english.

**Comment by wesmelo** [comment]
Well, i guess it would be nice

**Comment by LFeh** [comment]
Hi @javierojeda94, @wesmelo, how are you?

As I am Brazilian, this project ended up reaching more people in Brazil and consequently most of the tests here are in Portuguese.

Do you have suggestions for more open tests in English or other languages?

**Comment by javierojeda94** [comment]
Consider the next statement: 

> Simplemente necesito poder entender los problemas para intentar resolverlos pero no puedo entenderlos debido a que están en un idioma distinto al inglés o al español. 

Was it easy to understand? Probably. The thing here is that the problems seem to be very cool actually but I don't understand the requirements so I can't solve them :( The request is simple, is there someone able to translate them? I myself may try to translate a few of them but someone that speaks the language would do it pretty quickly I think and make this repo more accesible and interesting to other people

**Comment by LFeh** [comment]
@javierojeda94 I understand your question, but this repo is just an aggregator. We can ask to owners of challenges translate it to provide acessibility to non-brazilian people.

What can we do to improve this repository is increase de quantity of challenges in english. 

Do you know more challenges that could stay here?

**Comment by javierojeda94** [comment]
This would be awesome
> We can ask to owners of challenges translate it to provide acessibility to non-brazilian people.

I have some more challenges to share, how can I add them?

**Comment by LFeh** [comment]
You can open PR with challenges or send me here the link of the repositories that I add

**Comment by Gutto1** [comment]
Hello guys, I'm brazilian also, and I can translate the challenges on my free time. I think it would be nice to reach out as many people as we can. @LFeh, how can I contribute? maybe sending a PR with the translations and to which challenge they refer to?

**Comment by Aline09** [comment]
I can translate the challenges on my free time too. How can I help?

**Comment by javierojeda94** [comment]
I think that if we add a disclaimer at the beginning of the translation is more than enough, isn't it? 

Probably I'm saying *bs* is just an idea. At the end the original problems are also open source and some of them are MIT licensed, what do you guys think?

**Comment by wesmelo** [comment]
If you need help with the translation from PT-BR to ENG, i can help

**Comment by LucasLeandro1204** [comment]
The best thing to do is to create a fork of the challenge and translate it. Then submit here (in a new category maybe?) with a disclaimer saying that it's not the official challenge repo and probably the company is not hiring foreign people.

**Comment by LFeh** [comment]
Perfect @LucasLeandro1204, after translate you can link it here.

**Comment by Gabrielasalvo** [comment]
hey, how can i help with the translations? I would like to help!!!

**Comment by felipefialho** [comment]
@Gabrielasalvo You can to open a issue (or PR) on tests repository with your translation
