### ISSUE TITLE
Desafio da Accenture 404

### ISSUE THREAD

**Issue by rfdeoliveira** [felipefialho/frontend-challenges#60]
Fala, @felipefialho, beleza? O repo do desafio da [Accenture](https://github.com/acnrecife/Front-End-Test-Interview) não está mais disponível, e não consegui achar outro pra colocar no lugar =(

**Comment by felipefialho** [comment]
opa @rfdeoliveira, consegue abrir um pr removendo o teste?

abraços!

**Comment by rfdeoliveira** [comment]
Opa! Consigo sim, pode deixar =)
