### ISSUE TITLE
LojasKD

### ISSUE THREAD

**Issue by inaciocorrea** [felipefialho/frontend-challenges#61]
O link para o desafio ainda é válido mas a loja encerrou as operações.

Tentei subir um PR com o fixo mas tomei um toco rs

**Comment by LucasLeandro1204** [comment]
Acredito que não tem problema, visto que os desafios aqui presentes também são válidos pra praticar

**Comment by LucasLeandro1204** [comment]
Acho que seria interessante adicionar uma coluna de `status` na tabela, pra saber se a empresa ainda esta com o processo seletivo ativo ou não

**Comment by inaciocorrea** [comment]
Justo

**Comment by felipefialho** [comment]
@LucasLeandro1204 a idéia é legal, o problema é a escalabilidade disso já que teriamos que de tempos em tempos fazer um passadão para verificar se a vaga está ativa.
