### ISSUE TITLE
Add challenge level column

### ISSUE THREAD

**Issue by DiogoCercilio** [felipefialho/frontend-challenges#72]
I think It would be great to add the column to inform the level of the opportunity (beginner, intermediate, advanced) or maybe the position title that was published (Ex: Intermediate Fullstack Developer etc).

**Comment by felipefialho** [comment]
The problem is because it is relative. 

Some companies doesn't separate their challenges per levels, so this will need to be defined by us, but each person has the own vision about it and is extremely relative thing.

Do you understand?
