### ISSUE TITLE
Label with language in which a task is written

### ISSUE THREAD

**Issue by levaleks** [felipefialho/frontend-challenges#77]
Hello! Thank you @felipefialho for such a great repo. I suggest adding information to indicate in which language a task description is written. For instance: 

1) 
|Lang | Company | Stack | Test
|--|--|--|--
| pt | :brazil: [1STi](http://www.1sti.com.br/) | React | [Code →](https://github.com/1STi/desafio-frontend/)
| en | :gibraltar: [Addison Global - 1](http://www.addisongloballtd.com/) | React, Redux | [Code →](https://github.com/addisonglobal/frontend-technical-test)
| en |  :fr: [AirCall - 1](https://aircall.io/) | HTML, CSS & JS, React | [Code →](https://github.com/aircall/integration-test)

2)
|Lang | Country | Company | Stack | Test
|--|--|--|--|--
| pt | :brazil: | [1STi](http://www.1sti.com.br/) | React | [Code →](https://github.com/1STi/desafio-frontend/)
| en | :gibraltar: | [Addison Global - 1](http://www.addisongloballtd.com/) | React, Redux | [Code →](https://github.com/addisonglobal/frontend-technical-test)
| en | :fr: | [AirCall - 1](https://aircall.io/) | HTML, CSS & JS, React | [Code →](https://github.com/aircall/integration-test)

3)
|| Company | Stack | Test
|--|--|--|--
| :brazil: | [1STi](http://www.1sti.com.br/) | React | [[pt] Code →](https://github.com/1STi/desafio-frontend/)
| :gibraltar: | [Addison Global - 1](http://www.addisongloballtd.com/) | React, Redux | [[en] Code →](https://github.com/addisonglobal/frontend-technical-test)
| :fr: | [AirCall - 1](https://aircall.io/) | HTML, CSS & JS, React | [[en] Code →](https://github.com/aircall/integration-test)

What do you think?

**Comment by felipefialho** [comment]
Awesome 😍 , can you help me to add this information?

**Comment by levaleks** [comment]
Sure! Which way (1,2,3, or maybe another) do you prefer?

**Comment by felipefialho** [comment]
1 is perfect! Clean 😄
